using Microsoft.CodeAnalysis;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;

namespace Configurables;

[Generator(LanguageNames.CSharp)]
public partial class ConfigurablesGenerator : IIncrementalGenerator
{
    private record Target
    {
        public INamedTypeSymbol ClassSymbol { get; set; }
        public IEnumerable<ISymbol> ConfigurableMembers { get; set; }

        public Target(INamedTypeSymbol classSymbol, IEnumerable<ISymbol> configurables)
        {
            ClassSymbol = classSymbol;
            ConfigurableMembers = configurables;
        }
    }

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static context =>
        {
            context.AddSource("ConfigurableAttribute.cs", """
using System;

namespace Configurables
{
    [AttributeUsage(AttributeTargets.Field | AttributeTargets.Property, AllowMultiple = false, Inherited = false)]
    public sealed class ConfigurableAttribute : Attribute
    {
        public ConfigurableAttribute() {}
    }
}


""");
        });

        var source = context.SyntaxProvider.ForAttributeWithMetadataName(
            // target Attribute name
            "Configurables.ConfigurableAttribute",
            static (node, token) => true,
            static (context, token) => context)
            .Select(static (context, token) => {
                token.ThrowIfCancellationRequested();
                return (classSymbol: context.TargetSymbol.ContainingType, target: context.TargetSymbol);
            })
            .Collect()
            .SelectMany(static (targets, token) => {
                token.ThrowIfCancellationRequested();
                return targets.GroupBy<(INamedTypeSymbol classSymbol, ISymbol target), INamedTypeSymbol, Target>(elem => elem.classSymbol,
                                                                                                                  (key, elems) => new Target(key, elems.Select(e => e.target)),
                                       SymbolEqualityComparer.Default);
            });

        context.RegisterSourceOutput(source, Emit);
        context.RegisterSourceOutput(source.Collect(), CreateConfigSystem);

    }

    private static void Emit(SourceProductionContext context, Target target)
    {
        string fullTypeName = target.ClassSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)
            .Replace("global::", "")
            .Replace("<", "_")
            .Replace(">", "_");;
        var ns = target.ClassSymbol.ContainingNamespace;
        bool isGlobalNamespace = ns.IsGlobalNamespace;

        var configStructConstructor = $$"""
            public Config({{string.Join(", ", target.ConfigurableMembers.Select(m => $"{((IFieldSymbol)m).Type} __{m.Name}"))}})
            {
                {{string.Join("\n", target.ConfigurableMembers.Select(m => $"{m.Name} = __{m.Name};"))}}
            }
            """;

        context.AddSource($"{fullTypeName}.ConfigurablesGenerator.g.cs", $$"""
                          // <auto-generated/>
                          using UnityEngine;
                          #nullable enable

                          {{(isGlobalNamespace ? "" : $"namespace {ns} {{")}}
                          partial class {{target.ClassSymbol.Name}}
                          {
                              public struct Config
                              {
                                  {{string.Join("\n", target.ConfigurableMembers.Select(m => $"public readonly {((IFieldSymbol)m).Type} {m.Name};"))}}

                                  {{configStructConstructor}}
                              }

                              public void Configure(Config config)
                              {
                                  {{string.Join("\n", target.ConfigurableMembers.Select(m => $"{m.Name} = config.{m.Name};"))}}
                              }
                          }
                          {{(isGlobalNamespace ? "" : "}")}}

                          """);
    }

    private static void CreateConfigSystem(SourceProductionContext context, ImmutableArray<Target> targets)
    {
        var configSystemBase = $$"""
            using UnityEngine;

            public partial class ConfigSystem
            {
                {{string.Join("\n", targets.Select(t => $"[SerializeField] private IConfigProvider<{t.ClassSymbol.Name}.Config> m_ConfigProviderFor{t.ClassSymbol.Name};\n"
                                                   + "[SerializeField] private {t.ClassSymbol.Name} m_{t.ClassSymbol.Name};"))}}

                public void Configure()
                {
                    {{string.Join("\n", targets.Select(t => $"m_{t.ClassSymbol.Name}.Configure(m_ConfigProviderFor{t.ClassSymbol.Name}.GetConfig());"))}}
                }
            }
            """;
        context.AddSource("ConfigSystem.g.cs", configSystemBase);
    }
}
