using Microsoft.CodeAnalysis;
using System.Collections.Generic;
using System.Linq;

namespace Configurables;

[Generator(LanguageNames.CSharp)]
public partial class ConfigurablesGenerator : IIncrementalGenerator
{
    private record Target
    {
        public INamedTypeSymbol ClassSymbol { get; set; }
        public IEnumerable<ISymbol> ConfigurableMembers { get; set; }

        public Target(INamedTypeSymbol classSymbol, IEnumerable<ISymbol> configurables)
        {
            ClassSymbol = classSymbol;
            ConfigurableMembers = configurables;
        }
    }

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static context =>
        {
            context.AddSource("ConfigurableAttribute.cs", """
using System;

namespace Configurables
{
    [AttributeUsage(AttributeTargets.Field | AttributeTargets.Property, AllowMultiple = false, Inherited = false)]
    public sealed class ConfigurableAttribute : Attribute
    {
        public ConfigurableAttribute() {}
    }
}


""");
        });

        var source = context.SyntaxProvider.ForAttributeWithMetadataName(
            // target Attribute name
            "Configurables.ConfigurableAttribute",
            static (node, token) => true,
            static (context, token) => context)
            .Select(static (context, token) => {
                token.ThrowIfCancellationRequested();
                return (classSymbol: context.TargetSymbol.ContainingType, target: context.TargetSymbol);
            })
            .Collect()
            .SelectMany(static (targets, token) => {
                token.ThrowIfCancellationRequested();
                return targets.GroupBy<(INamedTypeSymbol classSymbol, ISymbol target), INamedTypeSymbol, Target>(elem => elem.classSymbol,
                                                                                                                  (key, elems) => new Target(key, elems.Select(e => e.target)),
                                       SymbolEqualityComparer.Default);
            });

        context.RegisterSourceOutput(source, Emit);

    }

    private static void Emit(SourceProductionContext context, Target target)
    {
        string fullTypeName = target.ClassSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)
            .Replace("global::", "")
            .Replace("<", "_")
            .Replace(">", "_");;
        var ns = target.ClassSymbol.ContainingNamespace;
        bool isGlobalNamespace = ns.IsGlobalNamespace;

        string targetsList = string.Join(", ", target.ConfigurableMembers.Select(s => s.Name));

        context.AddSource($"{fullTypeName}.ConfigurablesGenerator.g.cs", $$"""
                          // <auto-generated/>
                          using UnityEngine;
                          #nullable enable

                          {{(isGlobalNamespace ? "" : $"namespace {ns} {{")}}
                          partial class {{target.ClassSymbol.Name}}
                          {
                              void AddedLog()
                              {
                                  Debug.Log("targets: {{targetsList}}");
                              }
                          }
                          {{(isGlobalNamespace ? "" : "}")}}

                          """);
    }
}
